### ISSUE TITLE
代码句法错误

### ISSUE THREAD

**Issue by xxhg** [williamthegrey/tellyget#1]
Traceback (most recent call last):
  File "/bin/tellyget", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/tellyget/tellyget.py", line 58, in main
    programmes = guide.get_programmes(channels)
  File "/usr/local/lib/python3.10/site-packages/tellyget/guide.py", line 88, in get_programmes
    schedule = self.get_schedule(channel_id)
  File "/usr/local/lib/python3.10/site-packages/tellyget/guide.py", line 105, in get_schedule
    script = soup.find_all('script', string=re.compile('parent.jsonBackLookStr'))[0].string
IndexError: list index out of range

你好
可以帮忙看下这条代码错在哪里吗？
谢谢。

**Comment by xxhg** [comment]
delete
